### root api
GET http://localhost:8000/

# /CRUD
### fetch all task 
GET http://localhost:8000/api/v1/task/


### add new task
POST http://localhost:8000/api/v1/task/
Content-Type: application/json

{
   "task":"Cooking",
    "hr":100
}

### update or switch task
PATCH  http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "_id":"64d005947004f74390cd5256",
    "type":"bad"
}


### delete the task
DELETE  http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "ids":[
        "64d005947004f74390cd5258",
        "64d00640ec263ab2adf20aa9"
    ]
}